if: tag IS blank
sudo: false
language: node_js

env:
  - CLI_TIMEOUT=10000
node_js:
  - "8"
  - "lts/*"
  - "node"
before_script:
  - git clone --depth=1 --branch=LanguageTag-data-case https://github.com/shexSpec/shexTest.git ../shexTest
install: npm ci
cache: npm
script:
  - npm run test-all

notifications:
  email: false

# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
